// <auto-generated>
// This file is generated by GenerateUploaderFactory.cs.
// Do not edit manually; update the uploader service source instead.
using SnapX.Core.Upload.File;
using SnapX.Core.Upload.Img;
using SnapX.Core.Upload.Custom;
using SnapX.Core.Upload.Text;
using SnapX.Core.Upload.URL;
using SnapX.Core.Upload.SharingServices;
using SnapX.Core.Upload.BaseServices;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using SnapX.Core.Utils;
namespace SnapX.Core.Upload;

public static partial class UploaderFactory
{
public static List<IUploaderService> AllServices { get; } = new();
public static List<IGenericUploaderService> AllGenericUploaderServices { get; } = new();

public static Dictionary<ImageDestination, ImageUploaderService> ImageUploaderServices { get; } = new();
public static Dictionary<TextDestination, TextUploaderService> TextUploaderServices { get; } = new();
public static Dictionary<FileDestination, FileUploaderService> FileUploaderServices { get; } = new();
public static Dictionary<UrlShortenerType, URLShortenerService> URLShortenerServices { get; } = new();
public static Dictionary<URLSharingServices, URLSharingService> URLSharingServices { get; } = new();

private static void Register<T>(T service) where T : IUploaderService
{
    AllServices.Add(service);

    if (service is IGenericUploaderService generic)
        AllGenericUploaderServices.Add(generic);

    switch (service)
    {
        case ImageUploaderService i:
            ImageUploaderServices[i.EnumValue] = i;
            break;
        case TextUploaderService t:
            TextUploaderServices[t.EnumValue] = t;
            break;
        case FileUploaderService f:
            FileUploaderServices[f.EnumValue] = f;
            break;
        case URLShortenerService u:
            URLShortenerServices[u.EnumValue] = u;
            break;
        case URLSharingService s:
            URLSharingServices[s.EnumValue] = s;
            break;
    }
}



    static UploaderFactory()
    {
    Register(new AmazonS3NewFileUploaderService());
    Register(new BackblazeB2UploaderService());
    Register(new CustomFileUploaderService());
    Register(new DropboxFileUploaderService());
    Register(new EmailFileUploaderService());
    Register(new FTPFileUploaderService());
    Register(new GoogleCloudStorageNewFileUploaderService());
    Register(new GoogleDriveFileUploaderService());
    Register(new HostrFileUploaderService());
    Register(new OneDriveFileUploaderService());
    Register(new OwnCloudFileUploaderService());
    Register(new PlikFileUploaderService());
    Register(new PomfFileUploaderService());
    Register(new PushbulletFileUploaderService());
    Register(new PuushFileUploaderService());
    Register(new SharedFolderFileUploaderService());
    Register(new StreamableFileUploaderService());
    Register(new UguuFileUploaderService());
    Register(new YouTubeFileUploaderService());
    Register(new SeafileFileUploaderService());
    Register(new AzureStorageUploaderService());
    Register(new BoxFileUploaderService());
    Register(new JiraFileUploaderService());
    Register(new LobFileFileUploaderService());
    Register(new MediaFireFileUploaderService());
    Register(new MegaFileUploaderService());
    Register(new SendSpaceFileUploaderService());
    Register(new SulFileUploaderService());
    Register(new Vault_oooFileUploaderService());
    Register(new LambdaFileUploaderService());
    Register(new TransfershFileUploaderService());
    Register(new GooglePhotosImageUploaderService());
    Register(new CheveretoImageUploaderService());
    Register(new CustomImageUploaderService());
    Register(new FlickrImageUploaderService());
    Register(new ImageShackImageUploaderService());
    Register(new ImgurImageUploaderService());
    Register(new PhotobucketImageUploaderService());
    Register(new VgymeImageUploaderService());
    Register(new CustomTextUploaderService());
    Register(new GitHubGistTextUploaderService());
    Register(new HastebinTextUploaderService());
    Register(new OneTimeSecretTextUploaderService());
    Register(new Paste2TextUploaderService());
    Register(new Paste_eeTextUploaderService());
    Register(new PastebinTextUploaderService());
    Register(new SlexyTextUploaderService());
    Register(new UpasteTextUploaderService());
    Register(new PastieTextUploaderService());
    Register(new PrivateBinUploaderService());
    Register(new YourlsURLShortenerService());
    Register(new ZeroWidthURLShortenerService());
    Register(new VURLShortenerService());
    Register(new CustomURLShortenerService());
    Register(new VgdURLShortenerService());
    Register(new PolrURLShortenerService());
    Register(new QRnetURLShortenerService());
    Register(new KuttURLShortenerService());
    Register(new TinyURLShortenerService());
    Register(new IsgdURLShortenerService());
    Register(new FirebaseDynamicLinksURLShortenerService());
    Register(new TwoGPURLShortenerService());
    Register(new BitlyURLShortenerService());
    Register(new TurlURLShortenerService());
    Register(new CustomURLSharingService());
    Register(new BingVisualSearchSharingService());
    Register(new DeliciousSharingService());
    Register(new EmailSharingService());
    Register(new FacebookSharingService());
    Register(new GoogleLensSharingService());
    Register(new LinkedInSharingService());
    Register(new PinterestSharingService());
    Register(new PushbulletSharingService());
    Register(new RedditSharingService());
    Register(new StumbleUponSharingService());
    Register(new TumblrSharingService());
    Register(new VkSharingService());
    }
}
// </auto-generated>
