name: Bug Report
description: File a bug report.
labels: "bug"
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! If you need real-time help, join us on [Discord](https://discord.gg/ys3ZCzttVQ).
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues.
        required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what happened.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: What did you expect?
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of SnapX are you running?
      options:
        - 0.4.0
        - 0.3.0
        - 0.2.1
        - 0.2.0
        - 0.1.0
        - Nightly
        - Building from Source
      default: 0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: log-check
    attributes:
      label: Logs do not have PII
      description: Since SnapX is in development, logs may contain sensitive information such as API keys, file paths, or other personally identifiable information (PII). It is your responsibility to review and strip any PII before sharing log content.
      options:
        - label: There is no personally identifiable information in my logs.
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/emiliauh/snapx-reimagined/blob/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/emiliauh/snapx-reimagined/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true
