using System.Collections.Concurrent;
using System.IO.Hashing;
using System.Text;
using NeoSolve.ImageSharp.AVIF;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Webp;
using SixLabors.ImageSharp.Drawing.Processing;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.PixelFormats;
using SnapX.Core.Utils;
using SnapX.Core.Utils.Miscellaneous;
using Xdg.Directories;

namespace SnapX.Core.Media.Services;

public static class ThumbnailService
{
    // Bump whenever the rendered thumbnail pipeline changes (e.g. videos now
    // use the play-icon placeholder). The identity is part of the on-disk key,
    // so a version bump invalidates thumbnails generated by older builds.
    private const string ThumbnailFormatVersion = "v2";

    static ThumbnailService()
    {
        var imageConfig = Configuration.Default;
        imageConfig.ImageFormatsManager.SetEncoder(AVIFFormat.Instance, AVIFEncoder.Instance);
        imageConfig.ImageFormatsManager.SetDecoder(AVIFFormat.Instance, AVIFDecoder.Instance);
        imageConfig.ImageFormatsManager.AddImageFormatDetector(new PatchedAVIFImageFormatDetector());
    }
    private static readonly ConcurrentDictionary<string, string> _pathCache = new();
    private static readonly string CacheFolder = Path.Combine(BaseDirectory.CacheHome, SnapXL.AppName, "Thumbnails");
    private static readonly HttpClient _httpClient = HttpClientFactory.Get();
    private static readonly SemaphoreSlim _processingSemaphore = new(3, 3);

    public static async Task<string> GetCompatibleSourceAsync(string? source)
    {
        if (string.IsNullOrEmpty(source)) return string.Empty;

        string cacheIdentity = GetCacheIdentity(source);
        if (_pathCache.TryGetValue(cacheIdentity, out string? cachedPath) &&
            IsUsableCacheFile(cachedPath))
        {
            return cachedPath;
        }

        await _processingSemaphore.WaitAsync().ConfigureAwait(false);
        try
        {
            string result = await GenerateWebpThumbnail(source, cacheIdentity).ConfigureAwait(false);
            if (!string.Equals(result, source, StringComparison.Ordinal))
            {
                _pathCache[cacheIdentity] = result;
            }
            return result;
        }
        finally
        {
            _processingSemaphore.Release();
        }

    }

    private static async Task<string> GenerateWebpThumbnail(string source, string cacheIdentity)
    {
        if (_pathCache.TryGetValue(cacheIdentity, out var cachedPath) &&
            IsUsableCacheFile(cachedPath))
        {
            return cachedPath;
        }
        var isUrl = Uri.TryCreate(source, UriKind.Absolute, out var uri)
                     && (uri.Scheme == Uri.UriSchemeHttp || uri.Scheme == Uri.UriSchemeHttps);
        Directory.CreateDirectory(CacheFolder);

        var sourceBytes = Encoding.UTF8.GetBytes(cacheIdentity);
        var hashBytes = XxHash64.Hash(sourceBytes);
        var hashName = Convert.ToHexString(hashBytes).Replace("-", "") + ".webp";
        var cachePath = Path.Combine(CacheFolder, hashName);

        if (IsUsableCacheFile(cachePath)) return cachePath;

        string temporaryPath = cachePath + "." + Guid.NewGuid().ToString("N") + ".tmp";

        try
        {
            DebugHelper.Logger?.Debug($"ThumbnailService: Generating thumbnail for {(isUrl ? "URL" : "File")}: {source}");

            if (!isUrl && FileHelpers.IsVideoFile(source))
            {
                // A video does not need a decoded frame. Render a consistent
                // play-icon placeholder (a dark tile with a white triangle) so
                // the history row signals it is a video without paying the cost
                // of decoding a frame with ffmpeg.
                using Image videoIcon = CreateVideoPlayIcon(200, 150);
                await videoIcon.SaveAsync(temporaryPath, new WebpEncoder
                {
                    Quality = 70,
                    Method = WebpEncodingMethod.Fastest
                }).ConfigureAwait(false);
                File.Move(temporaryPath, cachePath, overwrite: true);
                return cachePath;
            }

            await using var imageStream = await GetImageStreamAsync(source, isUrl);
            using var image = await Image.LoadAsync(imageStream);
            image.Mutate(x => x.Resize(new ResizeOptions
            {
                Size = new Size(200, 150),
                Mode = ResizeMode.Max
            }));
            // CPU time is precious
            await image.SaveAsync(temporaryPath, new WebpEncoder()
            {
                Quality = 70,
                Method = WebpEncodingMethod.Fastest
            }).ConfigureAwait(false);

            // Publish only a complete image. This prevents the image loader from
            // reading a partially-written thumbnail during concurrent refreshes.
            File.Move(temporaryPath, cachePath, overwrite: true);

            return cachePath;
        }
        catch (Exception ex)
        {
            DebugHelper.Logger?.Debug($"ThumbnailService: Error during conversion: {ex.Message}");
            return source;
        }
        finally
        {
            try
            {
                if (File.Exists(temporaryPath)) File.Delete(temporaryPath);
            }
            catch (IOException)
            {
            }
        }
    }

    private static string GetCacheIdentity(string source)
    {
        bool isUrl = Uri.TryCreate(source, UriKind.Absolute, out var uri) &&
                     (uri.Scheme == Uri.UriSchemeHttp || uri.Scheme == Uri.UriSchemeHttps);
        if (isUrl) return "url:" + ThumbnailFormatVersion + ":" + source;

        try
        {
            string fullPath = Path.GetFullPath(source);
            var info = new FileInfo(fullPath);
            return info.Exists
                ? $"file:{ThumbnailFormatVersion}:{fullPath}\n{info.Length}\n{info.LastWriteTimeUtc.Ticks}"
                : "missing:" + ThumbnailFormatVersion + ":" + fullPath;
        }
        catch (Exception ex) when (ex is ArgumentException or NotSupportedException or PathTooLongException)
        {
            return "source:" + ThumbnailFormatVersion + ":" + source;
        }
    }

    private static bool IsUsableCacheFile(string? path)
    {
        if (string.IsNullOrWhiteSpace(path)) return false;
        try
        {
            // Interrupted writers previously left 36-byte WebP headers in the
            // cache. They are non-empty but cannot be decoded, leaving blank
            // history tiles because the cache incorrectly treats them as hits.
            return File.Exists(path) && new FileInfo(path).Length >= 128;
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException or NotSupportedException)
        {
            return false;
        }
    }

    private static async Task<Stream> GetImageStreamAsync(string source, bool isUrl)
    {
        if (!isUrl) return File.OpenRead(source);
        using var request = new HttpRequestMessage(HttpMethod.Get, source);

        request.Headers.Accept.ParseAdd("image/avif,image/webp,image/apng,image/*,*/*;q=0.8");

        request.Headers.ExpectContinue = true;

        var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);
        response.EnsureSuccessStatusCode();

        return await response.Content.ReadAsStreamAsync();

    }


    // Draws a simple video play-icon placeholder: a dark rounded tile with a
    // centered white triangle. Used for video history items so the row signals
    // "video" without decoding a frame.
    private static Image CreateVideoPlayIcon(int width, int height)
    {
        Image image = new Image<SixLabors.ImageSharp.PixelFormats.Rgba32>(width, height);
        image.Mutate(ctx =>
        {
            // Dark tile background.
            ctx.Fill(Color.FromRgb(28, 28, 30), new RectangleF(0, 0, width, height));

            // Centered white play triangle.
            int cx = width / 2;
            int cy = height / 2;
            int half = height / 4;
            PointF[] triangle =
            {
                new(cx - half / 2, cy - half),
                new(cx - half / 2, cy + half),
                new(cx + half * 1.4f, cy)
            };
            ctx.FillPolygon(Color.White, triangle);
        });
        return image;
    }

}
