<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>false</PublishAot>
    <PublishTrimmed>false</PublishTrimmed>
    <SelfContained>false</SelfContained>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../SnapX.Core/SnapX.Core.csproj" />
    <None Include="Pasteboard.m" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
