#!/usr/bin/env dotnet

#:sdk Microsoft.NET.Sdk

using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Diagnostics;

static string FindRepoRoot(string? startPath = null)
{
	startPath ??= Environment.CurrentDirectory;

	var dir = File.Exists(startPath)
		? new DirectoryInfo(Path.GetDirectoryName(Path.GetFullPath(startPath))!)
		: new DirectoryInfo(Path.GetFullPath(startPath));

	while (true)
	{
		try
		{
			if (File.Exists(Path.Combine(dir.FullName, "build.sh")))
				return dir.FullName;
		}
		catch (UnauthorizedAccessException)
		{
			// Skip directories we can't read
		}
		catch (IOException)
		{
			// Ignore transient filesystem issues
		}

		if (dir.Parent == null)
			break;

		dir = dir.Parent;
	}

	throw new InvalidOperationException(
		"Could not locate repo root (build.sh not found). "
			+ "Make sure this tool is executed from inside the SnapX repository."
	);
}

var root =
	FindRepoRoot(Environment.CurrentDirectory)
	?? throw new InvalidOperationException("Could not locate repo root (build.sh not found).");

string sourceRoot = Path.Combine(root, "SnapX.Core");
string uploaderFactoryPath = Path.Combine(sourceRoot, "Upload", "UploaderFactory.cs");

if (File.Exists(uploaderFactoryPath))
{
	try
	{
		File.Delete(uploaderFactoryPath);
	}
	catch
	{
		// Sillenceee
	}
	// return;
}

var regex = new Regex(
	@"public\s+class\s+(?<name>\w+UploaderService)\s*:\s*\w*UploaderService(?:\s*<[^>]+>)?",
	RegexOptions.Multiline | RegexOptions.Compiled
);

// Scan all .cs files for subclasses of UploaderService<>
var uploaderFiles = Directory
	.GetFiles(Path.Combine(sourceRoot, "Upload"), "*.cs", SearchOption.AllDirectories)
	.Where(f =>
	{
		if (f.EndsWith("UploaderFactory.cs", StringComparison.OrdinalIgnoreCase))
			return false;

		var content = File.ReadAllText(f);

		// Match lines like "class X : SomethingUploaderService" or "class X : SomethingUploaderService<...>"
		return regex.Match(content).Success;
	})
	.ToList();

Console.WriteLine($"Found {uploaderFiles.Count} UploaderService subclasses");
var registrations = new List<string>();

foreach (var file in uploaderFiles)
{
	var content = File.ReadAllText(file);
	var matches = regex.Matches(content);
	foreach (Match match in matches)
	{
		if (!match.Success)
			continue;
		var className = match.Groups["name"].Value.Trim();
		registrations.Add(className);
	}
}

if (!registrations.Any())
{
	Console.WriteLine("No uploader subclasses found.");
	return;
}
using var sw = new StreamWriter(uploaderFactoryPath, false);
sw.WriteLine("// <auto-generated>");
sw.WriteLine("// This file was forged in the Void.");
sw.WriteLine("//");
sw.WriteLine("// In another timeline, a Source Generator would have been used.");
sw.WriteLine("// That path was shown… and rejected.");
sw.WriteLine("//");
sw.WriteLine("// Instead, this code was written ahead of time,");
sw.WriteLine("// pulled from the darkness of the build step,");
sw.WriteLine("// and bound explicitly so NativeAOT would not forget it.");
sw.WriteLine("//");
sw.WriteLine("// Reflection was cast into the Void.");
sw.WriteLine("// Trimming was appeased.");
sw.WriteLine("// The uploaders now exist because they are *named*.");
sw.WriteLine("//");
sw.WriteLine("// \"We cannot blame these creatures. They are being led by a false prophet,\"");
sw.WriteLine("// Hunhow, if he reviewed this code");
sw.WriteLine("//");
sw.WriteLine("// DO NOT EDIT THIS FILE MANUALLY.");
sw.WriteLine("// Changes will be erased when the Void stirs again.");
sw.WriteLine();
sw.WriteLine("// This file is generated by GenerateUploaderFactory.cs");
sw.WriteLine("using SnapX.Core.Upload.File;");
sw.WriteLine("using SnapX.Core.Upload.Img;");
sw.WriteLine("using SnapX.Core.Upload.Custom;");
sw.WriteLine("using SnapX.Core.Upload.Text;");
sw.WriteLine("using SnapX.Core.Upload.URL;");
sw.WriteLine("using SnapX.Core.Upload.SharingServices;");
sw.WriteLine("using SnapX.Core.Upload.BaseServices;");
sw.WriteLine("using System.Collections.Generic;");
sw.WriteLine("using System.Diagnostics.CodeAnalysis;");
sw.WriteLine("using SnapX.Core.Utils;");
sw.WriteLine("namespace SnapX.Core.Upload;");
sw.WriteLine();
sw.WriteLine("public static partial class UploaderFactory");
sw.WriteLine("{");
sw.WriteLine(
	"""
public static List<IUploaderService> AllServices { get; } = new();
public static List<IGenericUploaderService> AllGenericUploaderServices { get; } = new();

public static Dictionary<ImageDestination, ImageUploaderService> ImageUploaderServices { get; } = new();
public static Dictionary<TextDestination, TextUploaderService> TextUploaderServices { get; } = new();
public static Dictionary<FileDestination, FileUploaderService> FileUploaderServices { get; } = new();
public static Dictionary<UrlShortenerType, URLShortenerService> URLShortenerServices { get; } = new();
public static Dictionary<URLSharingServices, URLSharingService> URLSharingServices { get; } = new();

private static void Register<T>(T service) where T : IUploaderService
{
    AllServices.Add(service);

    if (service is IGenericUploaderService generic)
        AllGenericUploaderServices.Add(generic);

    switch (service)
    {
        case ImageUploaderService i:
            ImageUploaderServices[i.EnumValue] = i;
            break;
        case TextUploaderService t:
            TextUploaderServices[t.EnumValue] = t;
            break;
        case FileUploaderService f:
            FileUploaderServices[f.EnumValue] = f;
            break;
        case URLShortenerService u:
            URLShortenerServices[u.EnumValue] = u;
            break;
        case URLSharingService s:
            URLSharingServices[s.EnumValue] = s;
            break;
    }
}


"""
);
sw.WriteLine();
sw.WriteLine("    static UploaderFactory()");
sw.WriteLine("    {");

foreach (var cls in registrations)
{
	sw.WriteLine($"    Register(new {cls}());");
}

sw.WriteLine("    }");
sw.WriteLine("}");
sw.WriteLine("// </auto-generated>");
// This doesn't just clear the C# buffer; 
// it forces the OS to finish the write before returning.
sw.Flush(); 
sw.Close();
Console.WriteLine("Running the git add command.");
try
{
	var processStartInfo = new ProcessStartInfo
	{
		FileName = "git",
		Arguments = $"add \"{uploaderFactoryPath}\"",
		WorkingDirectory = root,
		RedirectStandardOutput = true,
		RedirectStandardError = true,
		UseShellExecute = false,
		CreateNoWindow = true,
	};

	using var process = new Process();
	process.StartInfo = processStartInfo;
	process.Start();

	var output = process.StandardOutput.ReadToEnd();
	var error = process.StandardError.ReadToEnd();

	process.WaitForExit();

	if (process.ExitCode == 0)
	{
		Console.WriteLine("Successfully added UploaderFactory.cs to git.");
		if (!string.IsNullOrWhiteSpace(output))
			Console.WriteLine($"Git output: {output}");
	}
	else
	{
		Console.WriteLine($"Failed to add file to git. Exit code: {process.ExitCode}");
		if (!string.IsNullOrWhiteSpace(error))
			Console.WriteLine($"Git error: {error}");
	}
}
catch (Exception ex)
{
	Console.WriteLine($"Error running git add: {ex.Message}");
}

Console.WriteLine("UploaderFactory.cs updated with automatic registration.");
