<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>false</PublishAot>
    <PublishTrimmed>false</PublishTrimmed>
    <SelfContained>false</SelfContained>
    <PublishReadyToRun>false</PublishReadyToRun>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../SnapX.Core/SnapX.Core.csproj" />
    <Compile Include="../../SnapX.NativeMessagingHost/NativeMessagingHost.cs"
             Link="NativeMessagingHost.cs" />
  </ItemGroup>
</Project>
