title: SnapX
# Snapcraft forced me to change the name of the package because they believe they own the word snap.
# More specifically, when a package starts with those four letters.
# I surely hope this package rename won't confuse users.
name: ui-snapx
summary: Capture, share, and automate your screenshots.
description: |
  SnapX is a free, open-source, cross-platform tool that lets you capture or record any area of your screen and instantly share it with a single keypress.
  Upload images, videos, text, and more to multiple supported destinations—all with ease
  This is a port of the original ShareX application to Linux.
  It is not an official release and is not affiliated with the original ShareX project.
  This project is under development and is *not* ready for use.
  Supports PNG (including animated variant), WEBP (including animated variant), AVIF (including animated variant), JPEG, GIFs (should be smaller than your typical ShareX GIF), TIFF, and BMP image formats.
  Cross-platform OCR powered by PaddleOCR that rivals PowerToys OCR, TesseractOCR, & Windows 10 built in OCR in accuracy
version: '0.5.0'
license: GPL-3.0-or-later
source-code: "https://github.com/emiliauh/snapx-reimagined"
adopt-info: ui-snapx
grade: devel
base: core24
confinement: strict
compression: lzo
contact: "emiliauh@users.noreply.github.com"
issues: "https://github.com/emiliauh/snapx-reimagined/issues"
icon: "./usr/share/icons/256x256/apps/io.emiliauh.SnapXL.SnapX.png"
# By default, snaps have an epoch of ‘0’. When a new version breaks data compatibility with this old version, incrementing the epoch in the new release stops those old users automatically refreshing to the new version.
epoch: "0"

assumes:
  - snapd2.39
  - snap-env

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  # For the time being, Microsoft hasn't removed support for Arm32 NativeAOT... yet
  armhf:
    build-on: [armhf]
    build-for: [armhf]

# for screen capture & sounds
plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404

apps:
  ui-snapx:
    # Avalonia uses GNOME for some of its stuff. We just really need the base libraries.
    extensions: [gnome]
    command: usr/lib/snapx/snapx-ui
    # Snap has a issue detecting our icons and thus produces an error. Working on it.
    desktop: usr/share/applications/io.emiliauh.SnapXL.SnapX.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      PATH: $SNAP/ffmpeg-platform/usr/bin:$SNAP/bin:$PATH
    plugs:
      - network
      - alsa
      - pipewire
      - pulseaudio
      - audio-playback
      - audio-record # FFmpeg Screen Capture is coming soon
      - desktop
      - media-control # FFmpeg Screen Capture
#      - browser-native-messaging Super privileged interface
#plugs:
#  browser-native-messaging:
#    interface: personal-files
#    write:
#      - $HOME/.mozilla/native-messaging-hosts/host-manifest-firefox.json
#      - $HOME/.config/chromium/NativeMessagingHosts/host-manifest-chrome.json
#      - $HOME/.config/google-chrome/NativeMessagingHosts/host-manifest-chrome.json
#      - $HOME/.config/microsoft-edge/NativeMessagingHosts/host-manifest-chrome.json
#      - $HOME/.config/vivaldi/NativeMessagingHosts/host-manifest-chrome.json
#      - $HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/host-manifest-chrome.json
#      - $HOME/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/host-manifest-firefox.json

parts:
  ui-snapx:
    parse-info: [usr/share/metainfo/io.emiliauh.SnapXL.SnapX.metainfo.xml]
    plugin: nil
    override-build: |
      ./build.sh install --no-color --no-extended-chars --prefix /usr --dest-dir $SNAPCRAFT_PART_INSTALL
      rm $SNAPCRAFT_PART_INSTALL/usr/bin/snapx $SNAPCRAFT_PART_INSTALL/usr/lib/snapx/snapx
    build-packages:
      - git
      - clang
      - zlib1g-dev
      - libsm6
      - ca-certificates
      - libicu74
    build-environment:
      - PKGTYPE: SNAP
      - DisableGitVersionTask: 1
    stage-packages:
      - x11-xserver-utils  # for `xrandr`
      - pciutils           # for `lspci`
      - mesa-utils         # for `glxinfo
    source: ..
#    source-subdir: ..
    override-pull: |
      craftctl default
      ln -s "$CRAFT_PROJECT_DIR" ./packaging
      version=$(./build.sh --version | tail -n1)

      # Truncate the version to a maximum of 32 characters
      truncated_version=$(echo "$version" | cut -c1-32)

      # Set the version with truncation. Good luck everyone else! :)
      snapcraftctl set-version "$truncated_version"
  # TLS 1.3 support
  msquic:
    plugin: cmake
    source-type: git
    source: https://github.com/microsoft/msquic.git
    source-tag: v2.5.6
    cmake-parameters: [-DCMAKE_INSTALL_PREFIX=/usr]
lint:
  ignore:
    - library:
        - usr/lib/*/libEGL_mesa.so.*
        - usr/lib/*/libGLX_mesa.so.*
        - usr/lib/*/libicuio.so.*
        - usr/lib/*/libicutest.so.*
        - usr/lib/*/libicutu.so.*
        - usr/lib/*/libxcb-glx.so.*
        - usr/lib/*/libxcb-shm.so.*
        - usr/lib/*/libmsquic.so.*
